//174 pays
const countries = {
    "AF": { "name": "Afghanistan", "capital": "Kaboul", "continent": "Asie" },
    "ZA": { "name": "Afrique du Sud", "capital": "Pretoria/Le Cap/Bloemfontein", "continent": "Afrique" },
    "AL": { "name": "Albanie", "capital": "Tirana", "continent": "Europe" },
    "DZ": { "name": "Algérie", "capital": "Alger", "continent": "Afrique" },
    "DE": { "name": "Allemagne", "capital": "Berlin", "continent": "Europe" },
    "AN": { "name": "Angola", "capital": "Luanda", "continent": "Afrique" },
    "SA": { "name": "Arabie Saoudite", "capital": "Riyad", "continent": "Asie" },
    "AR": { "name": "Argentine", "capital": "Buenos aires", "continent": "Amérique" },
    "AM": { "name": "Arménie", "capital": "Erevan", "continent": "Asie" },
    "AU": { "name": "Australie", "capital": "Canberra", "continent": "Océanie" },
    "AT": { "name": "Autriche", "capital": "Vienne", "continent": "Europe"},
    "AZ": { "name": "Azerbaïdjan", "capital": "Bakou", "continent": "Asie" },
    "BS": { "name": "Bahamas", "capital": "Nassau", "continent": "Amérique" },
    "BD": { "name": "Bangladesh", "capital": "Dacca", "continent": "Asie" },
    "BE": { "name": "Belgique", "capital": "Bruxelles", "continent": "Europe" },
    "BZ": { "name": "Belize", "capital": "Belmopan", "continent": "Amérique" },
    "BJ": { "name": "Bénin", "capital": "Porto-Novo", "continent": "Afrique"},
    "BY": { "name": "Biélorussie", "capital": "Minsk", "continent": "Europe" },
    "MM": { "name": "Birmanie", "capital": "Naypyidaw", "continent": "Asie" },
    "BO": { "name": "Bolivie", "capital": "Sucre", "continent": "Amérique" },
    "BA": { "name": "Bosnie Herzégovine", "capital": "Sarajevo", "continent": "Europe" },
    "BW": { "name": "Botswana", "capital": "Gaborone", "continent": "Afrique" },
    "BT": { "name": "Bouthan", "capital": "Thimphou", "continent": "Asie" },
    "BR": { "name": "Brésil", "capital": "Brasilia", "continent": "Amérique" },
    "BN": { "name": "Brunei", "capital": "Bandar Seri Begawan", "continent": "Asie" },
    "BG": { "name": "Bulgarie", "capital": "Sofia", "continent": "Europe" },
    "BF": { "name": "Burkina Faso", "capital": "Ouagadougou", "continent": "Afrique" },
    "BI": { "name": "Burundi", "capital": "Gitega", "continent": "Afrique" },
    "KH": { "name": "Cambodge", "capital": "Phnom Penh", "continent": "Asie" },
    "CM": { "name": "Cameroun", "capital": "Yaoundé", "continent": "Afrique" },
    "CA": { "name": "Canada", "capital": "Ottawa", "continent": "Amérique" },
    "CL": { "name": "Chili", "capital": "Santiago", "continent": "Amérique" },
    "CH": { "name": "Chine", "capital": "Pékin", "continent": "Asie" },
    "CP": { "name": "Chypre", "capital": "Nicosie", "continent": "Europe" },
    "CO": { "name": "Colombie", "capital": "Bogota", "continent": "Amérique" },
    "CG": { "name": "Congo", "capital": "Brazzaville", "continent": "Afrique" },    
    "KP": { "name": "Corée du Nord", "capital": "Pyongyang", "continent": "Asie" },
    "KR": { "name": "Corée du Sud", "capital": "Séoul", "continent": "Asie" },
    "CR": { "name": "Costa Rica", "capital": "San José", "continent": "Amérique" },
    "CI": { "name": "Côte d'Ivoire", "capital": "Yamoussoukro", "continent": "Afrique" },
    "HR": { "name": "Croatie", "capital": "Zagreb", "continent": "Europe" },
    "CU": { "name": "Cuba", "capital": "La Havane", "continent": "Amérique" },
    "DK": { "name": "Danemark", "capital": "Copenhague", "continent": "Europe" },
    "DJ": { "name": "Djibouti", "capital": "Djibouti", "continent": "Afrique" },
    "EG": { "name": "Égypte", "capital": "Le Caire", "continent": "Afrique" },
    "AE": { "name": "Émirats Arabes Unis", "capital": "Abou Dabi", "continent": "Asie" },
    "EC": { "name": "Équateur", "capital": "Quito", "continent": "Amérique" },
    "ER": { "name": "Érythrée", "capital": "Asmara", "continent": "Afrique" },
    "ES": { "name": "Espagne", "capital": "Madrid", "continent": "Europe" },
    "EE": { "name": "Estonie", "capital": "Tallinn", "continent": "Europe" },
    "SZ": { "name": "Eswatini", "capital": "Mbabane", "continent": "Afrique" },
    "US": { "name": "États-Unis", "capital": "Washington", "continent": "Amérique" },
    "ET": { "name": "Éthiopie", "capital": "Addis-Abeba", "continent": "Afrique" },
    "FJ": { "name": "Fidji", "capital": "Suva", "continent": "Océanie" },
    "FI": { "name": "Finlande", "capital": "Helsinki", "continent": "Europe" },
    "FR": { "name": "France", "capital": "Paris", "continent": "Europe" },
    "GA": { "name": "Gabon", "capital": "Libreville", "continent": "Afrique" },
    "GM": { "name": "Gambie", "capital": "Banjul", "continent": "Afrique" },
    "GE": { "name": "Géorgie", "capital": "Tbilissi", "continent": "Europe" },
    "GH": { "name": "Ghana", "capital": "Accra", "continent": "Afrique" },
    "GR": { "name": "Grèce", "capital": "Athènes", "continent": "Europe" },
    "GL": { "name": "Groenland", "capital": "Nuuk", "continent": "Europe" },
    "GT": { "name": "Guatemala", "capital": "Guatemala", "continent": "Amérique" },
    "GN": { "name": "Guinée", "capital": "Conakry", "continent": "Afrique" },
    "GW": { "name": "Guinée Bissau", "capital": "Bissau", "continent": "Afrique" },
    "GQ": { "name": "Guinée Équatoriale", "capital": "Malabo", "continent": "Afrique" },
    "GY": { "name": "Guyana", "capital": "Georgetown", "continent": "Amérique" },
    "GF": { "name": "Guyane", "capital": "Cayenne", "continent": "Amérique" },
    "HT": { "name": "Haïti", "capital": "Port-au-Prince", "continent": "Amérique" },
    "HN": { "name": "Honduras", "capital": "Tegucigalpa", "continent": "Amérique" },
    "HU": { "name": "Hongrie", "capital": "Budapest", "continent": "Europe" },
    "IN": { "name": "Inde", "capital": "New Delhi", "continent": "Asie" },
    "ID": { "name": "Indonésie", "capital": "Jakarta", "continent": "Asie" },
    "IQ": { "name": "Irak", "capital": "Bagdad", "continent": "Asie" },
    "IR": { "name": "Iran", "capital": "Téhéran", "continent": "Asie" },
    "IE": { "name": "Irlande", "capital": "Dublin", "continent": "Europe" },
    "IS": { "name": "Islande", "capital": "Reykjavik", "continent": "Europe" },
    "IL": { "name": "Israël", "capital": "Jérusalem", "continent": "Asie" },
    "IT": { "name": "Italie", "capital": "Rome", "continent": "Europe" },
    "JM": { "name": "Jamaïque", "capital": "Kingston", "continent": "Amérique" },
    "JP": { "name": "Japon", "capital": "Tokyo", "continent": "Asie" },
    "JO": { "name": "Jordanie", "capital": "Amman", "continent": "Asie" },
    "KZ": { "name": "Kazakhstan", "capital": "Astana", "continent": "Asie" },
    "KE": { "name": "Kenya", "capital": "Nairobi", "continent": "Afrique" },
    "KG": { "name": "Kirghizistan", "capital": "Bichkek", "continent": "Asie" },
    "XK": { "name": "Kosovo", "capital": "Pristina", "continent": "Europe" },
    "KW": { "name": "Koweït", "capital": "Koweït", "continent": "Asie" },
    "LA": { "name": "Laos", "capital": "Vientiane", "continent": "Asie" },
    "LS": { "name": "Lesotho", "capital": "Maseru", "continent": "Afrique" },
    "LV": { "name": "Lettonie", "capital": "Riga", "continent": "Europe" },
    "LB": { "name": "Liban", "capital": "Beyrouth", "continent": "Asie" },
    "LR": { "name": "Libéria", "capital": "Monrovia", "continent": "Afrique" },
    "LY": { "name": "Libye", "capital": "Tripoli", "continent": "Afrique" },
    "LT": { "name": "Lituanie", "capital": "Vilnius", "continent": "Europe" },
    "LU": { "name": "Luxembourg", "capital": "Luxembourg", "continent": "Europe" },
    "MK": { "name": "Macédoine", "capital": "Skopje", "continent": "Europe" },
    "MG": { "name": "Madagascar", "capital": "Antananarivo", "continent": "Afrique" },
    "MY": { "name": "Malaisie", "capital": "Kuala Lumpur", "continent": "Asie" },
    "MW": { "name": "Malawi", "capital": "Lilongwe", "continent": "Afrique" },
    "ML": { "name": "Mali", "capital": "Bamako", "continent": "Afrique" },
    "FA": { "name": "Malouines", "capital": "Stanley", "continent": "Amérique" },
    "MO": { "name": "Maroc", "capital": "Rabat", "continent": "Afrique" },
    "MU": { "name": "Maurice", "capital": "Port-Louis", "continent": "Afrique" },
    "MR": { "name": "Mauritanie", "capital": "Nouakchott", "continent": "Afrique" },
    "MX": { "name": "Mexique", "capital": "Mexico", "continent": "Amérique" },
    "MD": { "name": "Moldavie", "capital": "Chisinau", "continent": "Europe" },
    "MN": { "name": "Mongolie", "capital": "Oulan-Bator", "continent": "Asie" },
    "ME": { "name": "Montenegro", "capital": "Podgorica", "continent": "Europe" },
    "MZ": { "name": "Mozambique", "capital": "Maputo", "continent": "Afrique" },
    "NA": { "name": "Namibie", "capital": "Windhoek", "continent": "Afrique" },
    "NP": { "name": "Népal", "capital": "Katmandou", "continent": "Asie" },
    "NI": { "name": "Nicaragua", "capital": "Managua", "continent": "Amérique" },
    "NE": { "name": "Niger", "capital": "Niamey", "continent": "Afrique" },
    "NG": { "name": "Nigéria", "capital": "Abuja", "continent": "Afrique" },
    "NO": { "name": "Norvège", "capital": "Oslo", "continent": "Europe" },
    "NC": { "name": "Nouvelle Calédonie", "capital": "Nouméa", "continent": "Océanie" },
    "NZ": { "name": "Nouvelle Zélande", "capital": "Wellington", "continent": "Océanie" },
    "OM": { "name": "Oman", "capital": "Mascate", "continent": "Asie" },
    "UG": { "name": "Ouganda", "capital": "Kampala", "continent": "Afrique" },
    "UZ": { "name": "Ouzbékistan", "capital": "Tachkent", "continent": "Asie" },
    "PK": { "name": "Pakistan", "capital": "Islamabad", "continent": "Asie" },
    "PS": { "name": "Palestine", "capital": "Jérusalem (Ramallah ?)", "continent": "Asie" },
    "PA": { "name": "Panama", "capital": "Panama", "continent": "Amérique" },
    "PG": { "name": "Papouasie Nouvelle Guinée", "capital": "Port Moresby", "continent": "Océanie" },
    "PY": { "name": "Paraguay", "capital": "Asuncion", "continent": "Amérique" },
    "NL": { "name": "Pays-Bas", "capital": "Amsterdam", "continent": "Europe" },
    "PE": { "name": "Pérou", "capital": "Lima", "continent": "Amérique" },
    "PH": { "name": "Philippines", "capital": "Manille", "continent": "Asie" },
    "PL": { "name": "Pologne", "capital": "Varsovie", "continent": "Europe" },
    "PR": { "name": "Porto Rico", "capital": "San Juan", "continent": "Amérique" },
    "PT": { "name": "Portugal", "capital": "Lisbonne", "continent": "Europe" },
    "QA": { "name": "Qatar", "capital": "Doha", "continent": "Asie" },
    "CF": { "name": "République Centrafricaine", "capital": "Bangui", "continent": "Afrique" },
    "DO": { "name": "République Dominicaine", "capital": "Saint-Domingue", "continent": "Amérique" },
    "CD": { "name": "République Démocratique du Congo", "capital": "Kinshasa", "continent": "Afrique" },
    "RO": { "name": "Roumanie", "capital": "Bucarest", "continent": "Europe" },
    "UK": { "name": "Royaume-Uni", "capital": "Londres", "continent": "Europe" },
    "RU": { "name": "Russie", "capital": "Moscou", "continent": "Europe" },
    "RW": { "name": "Rwanda", "capital": "Kigali", "continent": "Afrique" },
    "EH": { "name": "Sahara Occidental", "capital": "Laâyoune", "continent": "Afrique" },
    "SM": { "name": "Salomon", "capital": "Honiara", "continent": "Océanie" },
    "SV": { "name": "Salvador", "capital": "San Salvador", "continent": "Amérique" },
    "SN": { "name": "Sénégal", "capital": "Dakar", "continent": "Afrique" },
    "RS": { "name": "Serbie", "capital": "Belgrade", "continent": "Europe" },
    "SL": { "name": "Sierra Leone", "capital": "Freetown", "continent": "Afrique" },
    "SK": { "name": "Slovaquie", "capital": "Bratislava", "continent": "Europe" },
    "SI": { "name": "Slovénie", "capital": "Ljubljana", "continent": "Europe" },
    "SO": { "name": "Somalie", "capital": "Mogadiscio", "continent": "Afrique" },
    "SD": { "name": "Soudan", "capital": "Khartoum", "continent": "Afrique" },
    "SS": { "name": "Soudan du Sud", "capital": "Djouba", "continent": "Afrique" },
    "LK": { "name": "Sri Lanka", "capital": "Sri Jayawardenapura Kotte", "continent": "Asie" },
    "SE": { "name": "Suède", "capital": "Stockholm", "continent": "Europe" },
    "SW": { "name": "Suisse", "capital": "Berne", "continent": "Europe" },
    "SR": { "name": "Suriname", "capital": "Paramaribo", "continent": "Amérique" },
    "SY": { "name": "Syrie", "capital": "Damas", "continent": "Asie" },
    "TJ": { "name": "Tadjikistan", "capital": "Douchanbé", "continent": "Asie" },
    "TW": { "name": "Taïwan", "capital": "Taipei", "continent": "Asie" },
    "TZ": { "name": "Tanzanie", "capital": "Dodoma", "continent": "Afrique" },
    "TD": { "name": "Tchad", "capital": "N'Djaména", "continent": "Afrique" },
    "CZ": { "name": "Tchéquie", "capital": "Prague", "continent": "Europe" },
    "TH": { "name": "Thaïlande", "capital": "Bangkok", "continent": "Asie" },
    "TL": { "name": "Timor Oriental", "capital": "Dili", "continent": "Asie" },
    "TG": { "name": "Togo", "capital": "Lomé", "continent": "Afrique" },
    "TN": { "name": "Tunisie", "capital": "Tunis", "continent": "Afrique" },
    "TM": { "name": "Turkménistan", "capital": "Achgabat", "continent": "Asie" },
    "TU": { "name": "Turquie", "capital": "Ankara", "continent": "Europe" },
    "UA": { "name": "Ukraine", "capital": "Kiev", "continent": "Europe" },
    "UY": { "name": "Uruguay", "capital": "Montevideo", "continent": "Amérique" },
    "VA": { "name": "Vanuatu", "capital": "Port-Vila", "continent": "Océanie" },
    "VE": { "name": "Venezuela", "capital": "Caracas", "continent": "Amérique" },
    "VN": { "name": "Vietnam", "capital": "Hanoï", "continent": "Asie" },
    "YE": { "name": "Yémen", "capital": "Sanaa", "continent": "Asie" },
    "ZM": { "name": "Zambie", "capital": "Lusaka", "continent": "Afrique" },
    "ZW": { "name": "Zimbabwe", "capital": "Harare", "continent": "Afrique" }
};

//45 pays
const littleCountries = {
    "AI": { "name": "Anguilla", "capital": "The Valley", "continent": "Amérique" },
    "AB": { "name": "Antigua et Barbuda", "capital": "Saint John's", "continent": "Amérique" },
    "AW": { "name": "Aruba", "capital": "Oranjestad", "continent": "Amérique" },
    "BH": { "name": "Bahreïn", "capital": "Manama", "continent": "Asie" },
    "BB": { "name": "Barbade", "capital": "Bridgetown", "continent": "Amérique" },
    "BM": { "name": "Bermudes", "capital": "Hamilton", "continent": "Amérique" },
    "BQ": { "name": "Bonaire", "capital": "Kralendijk", "continent": "Amérique" },
    "CY": { "name": "Caïmans", "capital": "George Town", "continent": "Amérique" },
    "CN": { "name": "Canaries", "capital": "Santa Cruz/Las Palmas", "continent": "Afrique" },
    "CV": { "name": "Cap Vert", "capital": "Praia", "continent": "Afrique" },
    "CS": { "name": "Comores", "capital": "Moroni", "continent": "Afrique" },
    "CW": { "name": "Curaçao", "capital": "Willemstad", "continent": "Amérique" },
    "DM": { "name": "Dominique", "capital": "Roseau", "continent": "Amérique" },
    "FE": { "name": "Féroé", "capital": "Tórshavn", "continent": "Europe" },
    "GD": { "name": "Grenade", "capital": "Saint-Georges", "continent": "Amérique" },
    "GU": { "name": "Guam", "capital": "Hagåtña", "continent": "Océanie" },
    "GP": { "name": "Guadeloupe", "capital": "Pointe-à-Pitre", "continent": "Amérique" },
    "HI": { "name": "Hawaï", "capital": "Honolulu", "continent": "Amérique" },
    "MV": { "name": "Maldives", "capital": "Malé", "continent": "Asie" },
    "MA": { "name": "Malte", "capital": "La Valette", "continent": "Europe" },
    "NM": { "name": "Mariannes du Nord", "capital": "Saipan", "continent": "Océanie" },
    "MH": { "name": "Marshall", "capital": "Delap-Uliga-Darrit", "continent": "Océanie" },
    "MQ": { "name": "Martinique", "capital": "Fort de France", "continent": "Amérique" },
    "YT": { "name": "Mayotte", "capital": "Mamoudzou", "continent": "Afrique" },
    "FM": { "name": "Micronésie", "capital": "Palikir", "continent": "Océanie" },
    "MS": { "name": "Montserrat", "capital": "Plymouth", "continent": "Amérique" },
    "NR": { "name": "Nauru", "capital": "Yaren", "continent": "Océanie" },
    "PW": { "name": "Palaos", "capital": "Ngerulmud", "continent": "Océanie" },
    "FP": { "name": "Polynésie", "capital": "Papeete", "continent": "Océanie" },
    "RE": { "name": "Réunion", "capital": "Saint-Denis", "continent": "Afrique" },
    "BL": { "name": "Saint-Barthélemy", "capital": "Gustavia", "continent": "Amérique" },
    "ST": { "name": "Saint-Christophe-et-Nièves", "capital": "Basseterre", "continent": "Amérique" },
    "LC": { "name": "Sainte-Lucie", "capital": "Castries", "continent": "Amérique" },
    "MF": { "name": "Saint-Martin", "capital": "Marigot", "continent": "Amérique" },
    "VC": { "name": "Saint-Vincent-et-les-Grenadines", "capital": "Kingstown", "continent": "Amérique" },
    "WS": { "name": "Samoa", "capital": "Apia", "continent": "Océanie" },
    "AS": { "name": "Samoa Américaines", "capital": "Pago Pago", "continent": "Océanie" },
    "SP": { "name": "São Tomé-et-Principe", "capital": "São Tomé", "continent": "Afrique" },
    "SC": { "name": "Seychelles", "capital": "Victoria", "continent": "Afrique" },
    "TO": { "name": "Tonga", "capital": "Nuku'alofa", "continent": "Océanie" },
    "TR": { "name": "Trinité-et-Tobago", "capital": "Port-d'Espagne", "continent": "Amérique" },
    "TK": { "name": "Turques-et-Caïques", "capital": "Cockburn Town", "continent": "Amérique" },
    "TV": { "name": "Tuvalu", "capital": "Funafuti", "continent": "Océanie" },
    "UV": { "name": "Vierges Américaines", "capital": "Charlotte-Amélie", "continent": "Amérique" },
    "VG": { "name": "Vierges Britanniques", "capital": "Road Town", "continent": "Amérique" }
  };

  const littleCountriesQuiz = {
    "AI": { "name": "Anguilla", "capital": "The Valley", "continent": "Amérique" },
    "AB": { "name": "Antigua et Barbuda", "capital": "Saint John's", "continent": "Amérique" },
    "AW": { "name": "Aruba", "capital": "Oranjestad", "continent": "Amérique" },
    "BH": { "name": "Bahreïn", "capital": "Manama", "continent": "Asie" },
    "BB": { "name": "Barbade", "capital": "Bridgetown", "continent": "Amérique" },
    "BM": { "name": "Bermudes", "capital": "Hamilton", "continent": "Amérique" },
    "BQ": { "name": "Bonaire", "capital": "Kralendijk", "continent": "Amérique" },
    "CY": { "name": "Caïmans", "capital": "George Town", "continent": "Amérique" },
    "CN": { "name": "Canaries", "capital": "Santa Cruz/Las Palmas", "continent": "Afrique" },
    "CV": { "name": "Cap Vert", "capital": "Praia", "continent": "Afrique" },
    "CS": { "name": "Comores", "capital": "Moroni", "continent": "Afrique" },
    "CW": { "name": "Curaçao", "capital": "Willemstad", "continent": "Amérique" },
    "DM": { "name": "Dominique", "capital": "Roseau", "continent": "Amérique" },
    "FE": { "name": "Féroé", "capital": "Tórshavn", "continent": "Europe" },
    "GD": { "name": "Grenade", "capital": "Saint-Georges", "continent": "Amérique" },
    "GU": { "name": "Guam", "capital": "Hagåtña", "continent": "Océanie" },
    "GP": { "name": "Guadeloupe", "capital": "Pointe-à-Pitre", "continent": "Amérique" },
    "HI": { "name": "Hawaï", "capital": "Honolulu", "continent": "Amérique" },
    "MV": { "name": "Maldives", "capital": "Malé", "continent": "Asie" },
    "MA": { "name": "Malte", "capital": "La Valette", "continent": "Europe" },
    "NM": { "name": "Mariannes du Nord", "capital": "Saipan", "continent": "Océanie" },
    "MH": { "name": "Marshall", "capital": "Delap-Uliga-Darrit", "continent": "Océanie" },
    "MQ": { "name": "Martinique", "capital": "Fort de France", "continent": "Amérique" },
    "YT": { "name": "Mayotte", "capital": "Mamoudzou", "continent": "Afrique" },
    "FM": { "name": "Micronésie", "capital": "Palikir", "continent": "Océanie" },
    "MS": { "name": "Montserrat", "capital": "Plymouth", "continent": "Amérique" },
    "NR": { "name": "Nauru", "capital": "Yaren", "continent": "Océanie" },
    "PW": { "name": "Palaos", "capital": "Ngerulmud", "continent": "Océanie" },
    "FP": { "name": "Polynésie", "capital": "Papeete", "continent": "Océanie" },
    "RE": { "name": "Réunion", "capital": "Saint-Denis", "continent": "Afrique" },
    "BL": { "name": "Saint-Barthélemy", "capital": "Gustavia", "continent": "Amérique" },
    "ST": { "name": "Saint-Christophe-et-Nièves", "capital": "Basseterre", "continent": "Amérique" },
    "LC": { "name": "Sainte-Lucie", "capital": "Castries", "continent": "Amérique" },
    "VC": { "name": "Saint-Vincent-et-les-Grenadines", "capital": "Kingstown", "continent": "Amérique" },
    "WS": { "name": "Samoa", "capital": "Apia", "continent": "Océanie" },
    "AS": { "name": "Samoa Américaines", "capital": "Pago Pago", "continent": "Océanie" },
    "SP": { "name": "São Tomé-et-Principe", "capital": "São Tomé", "continent": "Afrique" },
    "SC": { "name": "Seychelles", "capital": "Victoria", "continent": "Afrique" },
    "TO": { "name": "Tonga", "capital": "Nuku'alofa", "continent": "Océanie" },
    "TR": { "name": "Trinité-et-Tobago", "capital": "Port-d'Espagne", "continent": "Amérique" },
    "TK": { "name": "Turques-et-Caïques", "capital": "Cockburn Town", "continent": "Amérique" },
    "TV": { "name": "Tuvalu", "capital": "Funafuti", "continent": "Océanie" },
    "UV": { "name": "Vierges Américaines", "capital": "Charlotte-Amélie", "continent": "Amérique" },
    "VG": { "name": "Vierges Britanniques", "capital": "Road Town", "continent": "Amérique" }
  };

// console.log("Taille countries : " + Object.keys(countries).length);
// console.log("Taille littleCountries : " + Object.keys(littleCountries).length);

const allCountries = { ...countries, ...littleCountries };

const allCountriesQuiz = { ...countries, ...littleCountriesQuiz };
